version: "3.7"
services:

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    networks:
      - envoymesh
    ports:
      - "10000:10000"
      - "9901:9901"

  service1:
    build:
      context: .
      dockerfile: Dockerfile-service
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      - envoymesh
    environment:
      - SERVICE_NAME=1
      
  go-control-plane:
    build:
      context: .
      dockerfile: Dockerfile-control-plane
    command: bin/example -debug
    healthcheck:
      test: nc -zv localhost 18000    

networks:
  envoymesh: {}
